# -*- coding: utf-8 -*-
"""DataSci_FinalProject_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLNgphr06eYGoRMcaCugHjYMamH8sR_T
"""

from google.colab import files
uploaded = files.upload()

import os
import gradio as gr
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma

#API key
os.environ["GOOGLE_API_KEY"] = "Your API key"

pdf_path = "PDPA Thailand LAW.pdf"

# Load PDF
loader = PyPDFLoader(pdf_path)
docs = loader.load()

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=2500,
    chunk_overlap=200
)
split_docs = text_splitter.split_documents(docs)

#embeddings
embeddings = GoogleGenerativeAIEmbeddings(model="gemini-embedding-001")

#vector database
vectorstore = Chroma.from_documents(
    documents=split_docs,
    embedding=embeddings
)

retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

#LLM
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.2
)

def ask_pdpa(question):
    if not question.strip():
        return "Please enter a question."

    retrieved_docs = retriever.invoke(question)
    context = "\n\n".join([doc.page_content for doc in retrieved_docs])

    prompt = f"""
You are a legal AI assistant specializing in the Thai Personal Data Protection Act (PDPA).
Explain clearly in simple English.
Mention the specific Section number from the text when possible.

Context:
{context}

Question:
{question}

Answer:
"""

    response = llm.invoke(prompt)
    return response.content

demo = gr.Interface(
    fn=ask_pdpa,
    inputs=gr.Textbox(lines=2, placeholder="Type your PDPA question here..."),
    outputs=gr.Textbox(lines=12, label="Answer"),
    title="Law for Dummies: PDPA Chatbot",
    description="Ask questions about the Thai Personal Data Protection Act (PDPA)."
)

demo.launch()